name: ariang ci

on:
  push:
    branches:
      - 'main'
    paths:
      - 'ariang/**'
  workflow_dispatch:

jobs:
  docker-publish:
    uses: ./.github/workflows/docker-publish-ghcr.yml
    with:
      context: ./ariang
      tags: ghcr.io/${{ github.repository_owner }}/ariang:latest
    secrets: inherit
