name: linuxbrew ci

on:
  push:
    branches:
      - 'main'
    paths:
      - 'linuxbrew/**'
  workflow_dispatch:

jobs:
  docker-publish:
    uses: ./.github/workflows/docker-publish-ghcr.yml
    with:
      context: ./linuxbrew
      tags: ghcr.io/${{ github.repository_owner }}/linuxbrew:latest
    secrets: inherit
